[2025-04-07T08:02:34.548+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.init.set_variables scheduled__2024-12-31T21:01:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
