[2025-04-07T09:02:21.498+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.get_news manual__2025-04-07T09:02:15.072461+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
