[2025-04-07T14:08:45.193+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T14:08:45.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS.process_news scheduled__2025-04-07T13:01:00+00:00 [queued]>
[2025-04-07T14:08:45.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS.process_news scheduled__2025-04-07T13:01:00+00:00 [queued]>
[2025-04-07T14:08:45.216+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-07T14:08:45.227+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_news> on 2025-04-07 13:01:00+00:00
[2025-04-07T14:08:45.237+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T14:08:45.239+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2025-04-07T14:08:45.239+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'RSS', 'process_news', 'scheduled__2025-04-07T13:01:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/RSS_DAG - Copy.py', '--cfg-path', '/tmp/tmpq2g3rckv']
[2025-04-07T14:08:45.241+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask process_news
[2025-04-07T14:08:45.275+0000] {task_command.py:426} INFO - Running <TaskInstance: RSS.process_news scheduled__2025-04-07T13:01:00+00:00 [running]> on host 5986bb29e517
[2025-04-07T14:08:45.335+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='RSS' AIRFLOW_CTX_TASK_ID='process_news' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T13:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T13:01:00+00:00'
[2025-04-07T14:08:45.335+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T14:08:45.344+0000] {log.py:232} WARNING - No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
[2025-04-07T14:10:28.361+0000] {log.py:232} WARNING - Device set to use cpu
[2025-04-07T14:10:28.383+0000] {base.py:84} INFO - Using connection ID 'redis_conn' for task execution.
[2025-04-07T14:10:28.398+0000] {base.py:84} INFO - Using connection ID 'mongo_conn' for task execution.
[2025-04-07T14:10:28.415+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.28.0.11', 5672)
[2025-04-07T14:10:28.416+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=101, family=2, type=1, proto=6, laddr=('172.28.0.18', 57542), raddr=('172.28.0.11', 5672)>
[2025-04-07T14:10:28.417+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2025-04-07T14:10:28.424+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-04-07T14:10:28.425+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-04-07T14:10:28.425+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2025-04-07T14:10:28.426+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2025-04-07T14:10:28.495+0000] {channel.py:536} INFO - Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2025-04-07T14:10:28.497+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff0de155550> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2025-04-07T14:10:28.497+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T14:10:28.498+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/RSS_DAG - Copy.py", line 67, in process_news
    channel.start_consuming()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/opt/airflow/dags/RSS_DAG - Copy.py", line 49, in action_on_msg
    if not collection.find_one({'guid': msg['guid']}):
                                        ~~~^^^^^^^^
KeyError: 'guid'
[2025-04-07T14:10:28.507+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=RSS, task_id=process_news, run_id=scheduled__2025-04-07T13:01:00+00:00, execution_date=20250407T130100, start_date=20250407T140845, end_date=20250407T141028
[2025-04-07T14:10:28.522+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task process_news ('guid'; 85)
[2025-04-07T14:10:28.570+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-07T14:10:28.585+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T14:10:28.590+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
