[2025-04-09T08:08:10.923+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T08:08:10.938+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Telegram.init.set_connections manual__2025-04-09T08:08:05.926950+00:00 [queued]>
[2025-04-09T08:08:10.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Telegram.init.set_connections manual__2025-04-09T08:08:05.926950+00:00 [queued]>
[2025-04-09T08:08:10.960+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-09T08:08:10.974+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): init.set_connections> on 2025-04-09 08:08:05.926950+00:00
[2025-04-09T08:08:10.992+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2508) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T08:08:10.994+0000] {standard_task_runner.py:63} INFO - Started process 2512 to run task
[2025-04-09T08:08:10.994+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Telegram', 'init.set_connections', 'manual__2025-04-09T08:08:05.926950+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/TG_MSG_DAG.py', '--cfg-path', '/tmp/tmpnz7m8pfd']
[2025-04-09T08:08:10.997+0000] {standard_task_runner.py:91} INFO - Job 216: Subtask init.set_connections
[2025-04-09T08:08:11.068+0000] {task_command.py:426} INFO - Running <TaskInstance: Telegram.init.set_connections manual__2025-04-09T08:08:05.926950+00:00 [running]> on host 5986bb29e517
[2025-04-09T08:08:11.159+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='Telegram' AIRFLOW_CTX_TASK_ID='init.set_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T08:08:05.926950+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T08:08:05.926950+00:00'
[2025-04-09T08:08:11.161+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T08:08:11.180+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T08:08:11.181+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '*** connections import /opt/***/connections.json']
[2025-04-09T08:08:11.197+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T08:08:13.301+0000] {subprocess.py:93} INFO - [[34m2025-04-09T08:08:13.300+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-04-09T08:08:13.307+0000] {subprocess.py:93} INFO - Could not import connection postgres_con: connection already exists.
[2025-04-09T08:08:13.308+0000] {subprocess.py:93} INFO - Could not import connection clickhouse_conn: connection already exists.
[2025-04-09T08:08:13.308+0000] {subprocess.py:93} INFO - Could not import connection rabbitmq_conn: connection already exists.
[2025-04-09T08:08:13.309+0000] {subprocess.py:93} INFO - Could not import connection mongo_conn: connection already exists.
[2025-04-09T08:08:13.309+0000] {subprocess.py:93} INFO - Could not import connection redis_conn: connection already exists.
[2025-04-09T08:08:13.635+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T08:08:13.636+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T08:08:13.657+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Telegram, task_id=init.set_connections, run_id=manual__2025-04-09T08:08:05.926950+00:00, execution_date=20250409T080805, start_date=20250409T080810, end_date=20250409T080813
[2025-04-09T08:08:13.693+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-09T08:08:13.711+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T08:08:13.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
