[2025-04-09T05:16:30.863+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T05:16:30.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Telegram.init.set_connections scheduled__2025-04-07T14:01:00+00:00 [queued]>
[2025-04-09T05:16:30.885+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Telegram.init.set_connections scheduled__2025-04-07T14:01:00+00:00 [queued]>
[2025-04-09T05:16:30.886+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-09T05:16:30.899+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): init.set_connections> on 2025-04-07 14:01:00+00:00
[2025-04-09T05:16:30.911+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T05:16:30.912+0000] {standard_task_runner.py:63} INFO - Started process 89 to run task
[2025-04-09T05:16:30.912+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Telegram', 'init.set_connections', 'scheduled__2025-04-07T14:01:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/TG_MSG_DAG.py', '--cfg-path', '/tmp/tmp8o8zrjz2']
[2025-04-09T05:16:30.914+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask init.set_connections
[2025-04-09T05:16:30.962+0000] {task_command.py:426} INFO - Running <TaskInstance: Telegram.init.set_connections scheduled__2025-04-07T14:01:00+00:00 [running]> on host 5986bb29e517
[2025-04-09T05:16:31.022+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='Telegram' AIRFLOW_CTX_TASK_ID='init.set_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T14:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T14:01:00+00:00'
[2025-04-09T05:16:31.023+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T05:16:31.031+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T05:16:31.032+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '*** connections import /opt/***/connections.json']
[2025-04-09T05:16:31.051+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T05:16:32.761+0000] {subprocess.py:93} INFO - [[34m2025-04-09T05:16:32.760+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-04-09T05:16:32.766+0000] {subprocess.py:93} INFO - Could not import connection postgres_con: connection already exists.
[2025-04-09T05:16:32.770+0000] {subprocess.py:93} INFO - Could not import connection clickhouse_conn: connection already exists.
[2025-04-09T05:16:32.771+0000] {subprocess.py:93} INFO - Could not import connection rabbitmq_conn: connection already exists.
[2025-04-09T05:16:32.772+0000] {subprocess.py:93} INFO - Could not import connection mongo_conn: connection already exists.
[2025-04-09T05:16:32.773+0000] {subprocess.py:93} INFO - Could not import connection redis_conn: connection already exists.
[2025-04-09T05:16:33.057+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T05:16:33.058+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T05:16:33.077+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Telegram, task_id=init.set_connections, run_id=scheduled__2025-04-07T14:01:00+00:00, execution_date=20250407T140100, start_date=20250409T051630, end_date=20250409T051633
[2025-04-09T05:16:33.129+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-09T05:16:33.147+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T05:16:33.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
