[2025-04-07T09:02:42.732+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.get_news scheduled__2025-01-04T07:01:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
